### ISSUE TITLE
[Idea] Add command palette/fuzzy search functionality to parts kit

### ISSUE THREAD

**Issue by gregkohn** [vigetlabs/craft-viget-base#14]
I'm certainly not trying to make the parts kit pages too heavy so I'm not 100% convinced this is a great idea but i have ~50 components in my Trust parts kit and ~100 overall variations. Would be nice to have a quick way to filter these down, whether via a search functionality identical to Storybook's or a modal similar to a command palette.

Storybook's implementation, which updates live as you type:
![image](https://user-images.githubusercontent.com/5114665/94154605-15818200-fe4c-11ea-927a-d7e7229288f7.png)
Example link: https://code.viget.com/spb-insider/?path=/story/achievement-icon--incomplete

**Comment by joshuapease** [comment]
@gregkohn Ah, looks like I don't have write access to this repo. 

I've got some search filtering working (although it's not truly Fuzzy). But we do have some keyboard shortcuts 🙌 !

**Comment by gregkohn** [comment]
@joshuapease hell yea! updated the settings, you should have access now
