### ISSUE TITLE
Check if Craft is installed before adding Phone Home job

### ISSUE THREAD

**Issue by yaychris** [vigetlabs/craft-viget-base#19]
I'm seeing an issue where the Phone Home job is attempting to push its job into the queue when Craft is not installed. This causes an exception because the queue table doesn't exist, and makes it impossible to access the installer via the web UI.

(Not sure what else this repo does, so might be worth making sure there isn't other code in here that should only run when Craft is installed.)

**Comment by davist11** [comment]
Fix released in version 2.0.1
