### ISSUE TITLE
Module interferes with 2FA plugin

### ISSUE THREAD

**Issue by amygtownsend** [vigetlabs/craft-viget-base#34]
2FA plugin repo: https://github.com/born05/craft-twofactorauthentication/

See [description of bug](https://github.com/born05/craft-twofactorauthentication/issues/54).

Disabling this module resolves the issue. We need to investigate what code within this module is interfering with the 2FA plugin functionality.

**Comment by davist11** [comment]
This should be fixed in version 3.1.1
