### ISSUE TITLE
[Parts Kit] Restrict `f` key shortcut to `f` key only

### ISSUE THREAD

**Issue by jeremyfrank** [vigetlabs/craft-viget-base#44]
Pressing `cmd+f` unexpectedly hides the parts list panel on the left, because the `f` key is a shortcut for hiding the panel. Can we restrict the shortcut to be `f` key **only** w/o any modifier keys pressed?

https://github.com/vigetlabs/craft-viget-base/blob/110103a6ee3e97fd954ab97a446a9ef1efcf2877/src/resources/js/parts-kit.js#L179-L181

**Comment by joshuapease** [comment]
@jeremyfrank This was bugging me too! PR is up!
